### ISSUE TITLE
Vundle in the repository

### ISSUE THREAD

**Issue by karimone** [maotora/my-dots#1]
Hi, on my configuration on github I added Vundle as submodule and at the first lunch of vim I just run `:PluginInstall` to have everything

**Comment by maotora** [comment]
Hi, I've been thinking of switching to vundle too, pathogen doesn't have any way to update and I [recently](http://vi.stackexchange.com/questions/9767/how-to-update-vim-plugins-with-pathogen-package-manager) just found out that pathogen isn't even a plugin manager.

I will update all my dot files maybe this week..

Thank you for your feedback!
